#+TITLE: Titre & mise en cohérence des objectifs du TIPE
#+AUTHOR: Malaury DUTOUR
#+OPTIONS: \n:t toc:nil date:nil
#+LATEX_HEADER: \usepackage[margin=0.9in]{geometry}

* Titre, ancrage et motivation
** Titre
L'impact physique de la course à pied.
** Ancrage
Le bitume est inévitable pour les coureurs en agglomération. Pourtant ce revêtement bien trop rigide n'est pas idéal pour cette pratique, c'est pour cela que les coureurs tentent au maximum de l'éviter. Qu'en est-il vraiment des traumatismes causés et comment les éviter ?
** Motivation
Etant moi même coureur amateur et habitant en agglomération, je suis directement concerné par le problème. J'ai souhaité examiner ce problème en réalisant l'acquisition de données mécaniques lors d'une course à pied en vude d'élaborer un modèle théorique.
* Mcot
** Positionnement thématique
+ Physique (mécanique)
+ Informatique (pratique)
** Mots clefs
+ Course à pied
+ Relevés podologiques
+ Ajustement de courbe
+ Jauge de contrainte
** Bibliographie commentée
Evaluer la douleur ressentie par un coureur demeure difficile, les chercheurs ont principalement recours à deux techniques pour mesurer les contraintes subies par le corps.
La première de celle-ci consiste en une analyse biomécanique du sportif [2] afin de principalement quantifier les forces mises en jeu lors de l'effort. Pour cela il est nécessaire de construire un modèle physique de la jambe avant de le soumettre à une simulation numérique [3]. Les principales difficultés de cette méthode résident dans la nécessité de connaître rigoureusement les propriétés des matériaux (tissus, ligaments, muscles, cartilages...) et de disposer d'une puissance de calcul importante en raison de la complexité du modèle. Elle requiert également de bonnes connaissances en physique des matériaux qu'un étudiant en classe préparatoire ne maitrise pas.
La seconde méthode, purement expérimentale, est en revanche plus accessible pour ce qui me concerne. Une première idée consisterait à faire une chronophotographie de la foulée [2],ce qui se heurte toutefois à un problème de précision dans les relevés des mesures bien qu'une photogrammétrie permettrait de pallier cette imprecision. Une seconde idée consisterait à utiliser une plateforme de force [2] qui évalue la force de réaction entre le sol et les pieds. Cette solution peut sembler idéale mais en pratique elle se heurte d'une part au fait que la plateforme est trop petite pour le coureur qui aurait des difficultés à la viser, et, d'autre part à une possible altération des mesures car le coureur modifierait sa foulée en visant la plaque de pression. Une autre idée consisterait à utiliser un tapis de course équipé de capteurs de pression en chaque point de la surface du tapis [1]. Ce type de matériel est utilisé par les podologues en raison de sa praticité pour établir précisément le diagnostique podologique du patient. Idéale sur le plan technique, cette idée est malheureusement très onéreuse à mettre en oeuvre.
Heureusement, il est possible de restreindre l'étude à seulement quelques points stratégiques du pied et ensuite d'extrapoler les résultats au reste de la surface d'appui [3]. L'avantage de cette solution que j'ai ainsi retenue est qu'elle repose sur des ressources abordables et permet de faire des relevés non pas uniquement sur un tapis de course mais sur tout type de surface ce qui permettra un relevé de mesures lors d'une course en environnement urbain.
** Problématique retenue
Mettre en évidence les traumatismes causés par la course à pied urbaine suivant différents chaussages et type de foulée.
** Objectifs du TIPE
Je me propose:
+ De réaliser un dispositif de relevés podologiques.
+ D'effectuer des relevés avec ce dispositif sur des surfaces de courses et des chaussures différentes.
+ De conclure sur l'influence du bitume sur les traumatismes du coureur.
+ De proposer un chaussage adapté à la pratique de la course à pied en ville.

** Liste des références bibliographiques
*** Référence 1
*Thèse de Stephane VERMOND :* /Gestion des modifications podales et des pressions plantaires en ultra-trail par des semelles orthopédiques équipées de barres rétro-capitales métatarsienne/
*** Référence 2
*Thèse de Caroline DIVERT :* /Influence du chaussage sur les caractéristiques mécaniques et le coût énergétique de la course à pied/
*** Référence 3
*Thèse de Tristan Tarrade :* /Conception et fabrication additive de semelles orthopédiques: simulation numérique, évaluation biomécanique et système expert/
* Déroulé Opérationnel du TIPE
 * Recherche et réflexion sur un dispositif expérimental pouvant répondre à la problématique.
 * Conception et réalisation du circuit éléctronique.
 * Calibration en utilisant une régression linéaire. Echec:données non fiables pour des faibles valeurs de pression.
 * Solution: programmation d'un algorithme d'ajustement de courbe pour la calibration
 * Relevés sur surfaces variées avec différentes chaussures.
 * Exploitation des mesures et établissement d'un modèle rhéologique.
